# Generated by Django 2.2.4 on 2021-12-05 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('friends_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendships',
            name='friender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='the_friender', to='friends_app.User'),
        ),
    ]
